### ISSUE TITLE
Need to correct example

### ISSUE THREAD

**Issue by subbuv26** [dkershner6/switch-case-action#5]
```
      - uses: dkershner6/switch-case-action@v1
        id: switch-case
        with:
          default: "its the default"
          conditionals-with-values: |
            ${{ 'test' == 'not-test' }} => shouldnt be this one
            ${{ 'test' == 'still-not-test' }} => correctAnswer
          
      - run: echo ${{ steps.switch-case.outputs.value }} # its the default
```

Should be

```
      - uses: dkershner6/switch-case-action@v1
        id: switch-case
        with:
          default: "its the default"
          conditionals-with-values: |
            ${{ 'test' == 'not-test' }} => shouldnt be this one
            ${{ 'test' == 'still-not-test' }} => shouldnt be this one, too
          
      - run: echo ${{ steps.switch-case.outputs.value }} # its the default
```
